-- TimescaleDB Support - Rollback
--
-- This migration created the TimescaleDB extension if it was available.
-- To remove TimescaleDB support:
--
-- 1. The application will handle cleanup if configured to do so
-- 2. Manual removal requires:
--    a. Convert hypertable back to regular table (if applicable)
--    b. Drop the extension: DROP EXTENSION IF EXISTS timescaledb CASCADE;
--
-- Note: Dropping TimescaleDB extension will CASCADE and remove dependent objects.
-- Ensure logging.entries is converted back to a regular table first if needed.
